### ISSUE TITLE
suppress urls in bootstrap 3...

### ISSUE THREAD

**Issue by DavidEschmeyer** [alamnaryab/Print-Preview-jquery-plugin#1]
Hi!  Cool plugin.

Question how do i suppress url's (bootstrap 3 includes url's  and they look ugly in the printout)?
i need somethign like
@media print { a[href]:after { content: none !important; }}
but im not sure how to tie that into the popup... how to pass it through your styles variable...

**Comment by alamnaryab** [comment]
See readme at githubu can pass url css as string in style option

Sent from Yahoo Mail on Android 
 
  On Tue, Oct 15, 2019 at 9:36 PM, David Eschmeyer<notifications@github.com> wrote:   
Hi! Cool plugin.

Question how do i suppress url's (bootstrap 3 includes url's and they look ugly in the printout)?
i need somethign like
@media print { a[href]:after { content: none !important; }}
but im not sure how to tie that into the popup... how to pass it through your styles variable...

**Comment by DavidEschmeyer** [comment]
Thanks for answering!  yeah i tried your example:
`<script type="text/javascript">
        $(function(){
            $("#btnPrint").printPreview({
                obj2print:'#divBilling_1',
                width:'1100',
                title:'<?php echo $borrowerName?>',
		style:'<style>#divBilling_1:background:red;</style>'`

but it did not color anything red... so i did not know if the format was correct.  So i did not move on to trying to suppress the urls

**Comment by DavidEschmeyer** [comment]
ok a working snippet is: 
style:'<style>#divBilling_1{background:red;}</style>'

so now i got it.  You may want to update your example snippet.  :)

**Comment by DavidEschmeyer** [comment]
now i can move on to urls...

**Comment by DavidEschmeyer** [comment]
style:'<style>a[href]:after { content: none !important; }</style>'

;)  you may want to share that with your community, it works and hides the bootstrap urls
